linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - staticcheck
    - govet
    - revive
    - ineffassign
    - gomodguard
    - gofmt
    - unused
    - gofumpt

linters-settings:
  golint:
    min-confidence: 0

  misspell:
    locale: US

    # Choose whether or not to use the extra rules that are disabled
    # by default
    extra-rules: false

issues:
  exclude-use-default: false
  exclude:
    - instead of using struct literal
    - should have a package comment
    - error strings should not be capitalized or end with punctuation or a newline
